% -------------------------------------------------------------------
%  Generated by MATLAB on 17-Feb-2022 18:50:23
%  MATLAB version: 9.11.0.1769968 (R2021b)
% -------------------------------------------------------------------
                                

y_scale = cell(1, 1);
y_scale{1} = 'Linear';

x_scale = cell(1, 1);
x_scale{1} = 'Linear';

y_label = cell(1, 1);
y_label{1} = '';

x_label = cell(1, 1);
x_label{1} = '';

checkbox = cell(1, 1);
checkbox{1} = 'false';

legends = cell(1, 1);
legends{1} = '';

ynot = cell(1, 1);
ynot{1} = 'false';

xnot = cell(1, 1);
xnot{1} = 'false';

style = '--';

width = cell(1, 1);
width{1} = '2';

marker = 'none';

markerSize = cell(1, 1);
markerSize{1} = '40';

colourType = cell(1, 1);
colourType{1} = 'Multiple Data Sets';

invertY = cell(1, 1);
invertY{1} = 'Off';

invertX = cell(1, 1);
invertX{1} = 'Off';

lowerX = cell(1, 1);
lowerX{1} = '500';

upperX = cell(1, 1);
upperX{1} = '4500';

lowerY = cell(1, 1);
lowerY{1} = '40';

upperY = cell(1, 1);
upperY{1} = '100';

preset = cell(1, 1);
preset{1} = 'Default';

